global:
  scrape_interval: 5s
  evaluation_interval: 10s

rule_files:
  - "/etc/prometheus/rules/*.yaml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'sentinel-api'
    static_configs:
      - targets: ['api:8080']